### ISSUE TITLE
Create end user how-to file

### ISSUE THREAD

**Issue by rachelshekar** [terraref/computing-pipeline#15] opened 2015-10-14 14:06 UTC
Includes what Rob is writing about Clowder, which is aimed at the API protocols
Also should include uploading file and using data, for less technical audience

**Comment by max-zilla** [comment] 2015-11-10 18:53
Here are two attachments to serve as an example of uploading a file via API. **Both are .txt so I can attach them here, but the extensions should actually be .py and .sh respectively.**

**Both are configured to connect to Nebula Clowder instance, but valid username and password should be provided. Directory and filename will obviously need to be adjusted.**

[TERRAClowderUploadPython.txt](https://github.com/terraref/computing-pipeline/files/31125/TERRAClowderUploadPython.txt)
* **TERRAClowderUploadPython.py** will upload file(s) to Nebula Clowder instance via API. One can specify multiple images in a directory to upload. **Requires [Requests 2.8.1](http://docs.python-requests.org/en/latest/) Python library** to issue POST. Written for Python 3.x.

[TERRAClowderUploadCurl.txt](https://github.com/terraref/computing-pipeline/files/31124/TERRAClowderUploadCurl.txt)
* **TERRAClowderUploadCurl** is a bash script that shows how to issue a POST in a single line using cURL, although I break out 3 strings to make modification easier here. In a windows environment cURL binaries can be found [here](http://curl.haxx.se/download.html).

**Comment by dlebauer** [comment] 2015-11-10 19:58
@max-zilla Please add these to a /scripts/ directory in this repository. Even if this is just a first draft, it will provide versioning as well as language-aware syntax highlighting (if given .py / .sh extensions).

**Comment by max-zilla** [comment] 2015-11-10 20:03
Just pushed to the repo with the correct file extensions.

**Comment by max-zilla** [comment] 2016-01-26 16:32
Current plan is to collect all documentation in the terraref documentation repo. My example scripts should be integrated into that location for consistency.

**Comment by dlebauer** [comment] 2016-02-04 17:22
dupe of #42?

**Comment by max-zilla** [comment] 2016-02-04 17:40
Migrated from #42...

[Prototype.Architecture.pptx](https://github.com/terraref/computing-pipeline/files/117908/Prototype.Architecture.pptx) (architecture slides from myself and @jdmaloney)

**Comment by max-zilla** [comment] 2016-03-11 20:57
I'm going to close this since files have been created. We should create more issues in the /documentation repo as we have specific needs. I will create one to address action items from this issue -
https://github.com/terraref/documentation/issues/5

**Closed by max-zilla** 2016-03-11 20:57 UTC
Labels: 1 - Ready
