### ISSUE TITLE
Irregular 3D scanner data in new calibration files

### ISSUE THREAD

**Issue by ZongyangLi** [terraref/computing-pipeline#141] opened 2016-08-08 15:49 UTC
### Description

Our lab is analyzing re-calibrated 3D data in: "/MovingSensor.reproc2016-8-3/scanner3DTop/" in Globus. There is some unexpected situation in new calibration files here:
1. For some of the 3D scanner data, the folders that contain this data do not have the associate files. Some examples: 
   "/MovingSensor.reproc2016-8-3/scanner3DTop/2016-05-04/2016-05-04__15-42-38-654/"
   "/MovingSensor.reproc2016-8-3/scanner3DTop/2016-05-27/2016-05-27__15-48-51-604/"
   "/MovingSensor.reproc2016-8-3/scanner3DTop/2016-06-08/2016-06-08__00-11-35-026/"
2. No points in ply file. This problem only occur in some early season data:
   "/MovingSensor.reproc2016-8-3/scanner3DTop/2016-05-15/"
   "/MovingSensor.reproc2016-8-3/scanner3DTop/2016-05-16/"
3. For some of the data, plant looks tilted to one side. It seems that once "Gantry Position Z"(parameter in json file) changed, this "plant tilted" would be happened:
   "/MovingSensor.reproc2016-8-3/scanner3DTop/2016-05-22/"
   "/MovingSensor.reproc2016-8-3/scanner3DTop/2016-05-30/"
   "/MovingSensor.reproc2016-8-3/scanner3DTop/2016-06-08/"

These problems might affect the estimation of plant's traits.

**Comment by dlebauer** [comment] 2016-08-08 15:57
Do you have any thoughts @smarshall-bmr @TinoDornbusch @rjstrand ?

**Comment by smarshall-bmr** [comment] 2016-08-08 16:25
@solmazhajmohammadi could probably tell you more about this. The empty folder/blank plys/tilted plants were known issues but I thought that all of the incorrectly generated ply files have been rewritten/replaced. Some may have been missed?

**Comment by solmazhajmohammadi** [comment] 2016-08-08 20:52
1. Original data is available in the server and in the old 3D scanner folder ("/MovingSensor/scanner3DTop/"). 
PLY worker was stopped during the processing data, probably missing data is related to this issue.  I will make sure to keep record of any unwanted restart for the next run. 

2. For the empty pointclouds we can delete them from the server for the next processing. 

3. Some of the parameters in the controller need to be adjusted. Pointclouds are tilted when the scans started from y=22m. (Scans starting from y=0 should be OK. )
You should see the same issue even in the early scans. @ZongyangLi I keep you updated when it is fixed.

**Comment by ZongyangLi** [comment] 2016-08-08 21:31
@solmazhajmohammadi Thanks for your reply!
For "tilted plants", I just want to let you know that it is not only happened when the scans started from y=22m. In the folder I provided(full day data), both side(west/east scans) pointclouds are tilted in reprocessing data.

**Comment by rachelshekar** [comment] 2016-08-17 19:51
has your question been answered @ZongyangLi ?

**Comment by ZongyangLi** [comment] 2016-08-18 14:29
so far as I know, these Irregular 3D scanner data still exist in the newest dataset.

**Comment by dlebauer** [comment] 2016-08-18 14:39
@solmazhajmohammadi could you please investigate and on this error?

Is the incorrect reporting of the z axis related to this? If not, could you or @ZongyangLi please create a new issue?

**Comment by solmazhajmohammadi** [comment] 2016-08-18 15:09
We are working to fix the issue. 
Regarding Z axis, it might be the gantry position. Till 07/04, Z axis was set to 3.615 and on 07/07, it has been set to 3.915m.

**Comment by rachelshekar** [comment] 2016-10-05 13:39
@solmazhajmohammadi : is this fixed?

**Comment by solmazhajmohammadi** [comment] 2017-01-05 17:42
@ZongyangLi @max-zilla @dlebauer 
I checked the data, irregular pointcloud data caused by Fraunhofer software bug. It should be fixed now, you can skip those data.

**Comment by rachelshekar** [comment] 2017-01-12 17:30
@ZongyangLi - please let us know if this is fixed.

**Comment by ZongyangLi** [comment] 2017-01-12 17:37
@rachelshekar I think this issue should be closed since it's for season 1.

I guess we are talking about unexpected data in season 2 from 10/13 to 11/04 which I mentioned in #210 . And from @solmazhajmohammadi we know that 3d data for those days are not able to fixed.

**Comment by dlebauer** [comment] 2017-01-13 18:37
@ZongyangLi if these data can not be fixed, will the extractor skip them? Does there need to be some sort of QA flag in these directories, should they be moved to a bad data folder, or should we delete them?

**Comment by dlebauer** [comment] 2017-01-13 18:39
In short, before closing I want to make sure that we have a robust way of handling these so that we don't end up accidentally processing them with the extractors and inserting errors into downstream datasets.

**Comment by ZongyangLi** [comment] 2017-01-13 20:08
@dlebauer I think they should not remain in the folder.

**Comment by dlebauer** [comment] 2017-01-13 20:20
@jdmaloney how do you suggest we handle these files (scanner3DTop from 10/3-11/14)? I wouldn't want to break the transfer logs / file checks or have them missing without explanation (e.g. if we just deleted or moved the files). 

@ZongyangLi what would it take to have the extractor skip these dates ... e.g. if a filename triggers the extractor, would it be sufficient to append the filenames with something like `_error`?

Or move the files and maintain the directory structure. In any case (moving, renaming, deleting). It could be helpful to create a README that links to this issue, the deleted or moved files, and a summary for future users.

Or, perhaps there is a more generic high-level solution, like having Clowder always ignore directories that contain a file named `dontrun` or similar ( @robkooper @max-zilla)?

**Comment by craig-willis** [comment] 2018-06-13 18:42
This is a stale issue with no comments in last 2 months. Please create new issues if work remains or put this content in the documentation.

**Closed by craig-willis** 2018-06-13 18:42 UTC
Labels: discussion
