### ISSUE TITLE
Confirm that plot boundaries for sorghum crop 2 generated from field scanner coordinates are consistent with those based on RTK GPS

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#187] opened 2016-10-14 22:38 UTC
Update: they don't match, so will make new polygons. https://github.com/terraref/computing-pipeline/issues/187#issuecomment-256760060 below:

For reference, we have two sets of polygons
1. those made by @tingli3 based on gantry measurements (transformed from gantry xy) these are already in BETYdb and can be queried as json here: https://terraref.ncsa.illinois.edu/bety/api/beta/sites?sitename=~Season+2&limit=none&key=
2. those made by @anfrench, used by @rickw-ward and exported to [json](https://github.com/terraref/computing-pipeline/files/553385/Rick_JSON.zip) by @Mamatemenrs .

(current hypothesis) The reason these differ is that (1) were two row plots and (2) were the same plots after they were a) combined into four row plots, and b) subset to just the inner two rows. (2) should be used for summarizing plot level metrics since they exclude border rows.
- [x] @Mamatemenrs please test my hypothesis by comparing and mapping these (similar to the map in https://github.com/terraref/computing-pipeline/issues/187#issuecomment-256248318 but with only the 'Season 2' plots from BETYdb
- [x] @tingli3 The next step is to create the BETYdb insert statements for these polygons - they will be listed as new 'sites'. But instead of `Plot 123` the sitename field should have `Row x Col y` (where x and y are integers of the row and column fields).
  - an alternative would be to do the polygon combining and subsetting the polygons that already exist. If this is easy, go for it. However, these plots have already been defined by @rickw-ward and @anfrench.

---

FYI (@robkooper and @gsrohde)  this is where we will need to begin combining sites using the geometry field (related to PecanProject/bety#444) ... so if someone queries for plot 1 they can find all contained or intersecting points and polygons. Developing these queries can wait until we have data and more specific use cases.

---
- @anfrench created a shape file that @rickw-ward has been using 
  [sorghumexpfall2016v5.zip](https://github.com/terraref/computing-pipeline/files/530579/sorghumexpfall2016v5.zip)
- @tingli3 created polygons based on @smarshall-bmr range and row measurements in gantry coordinate systems in https://github.com/terraref/computing-pipeline/issues/174

We should confirm that these are in alignment
- [x] @anfrench please provide the shapefile
- [ ] polygons for season 2 are here: https://terraref.ncsa.illinois.edu/bety/api/beta/sites?key=9999999999999999999999999999999999999999
- [ ] Please confirm that these align, and where we need to handle differences.

**Comment by anfrench** [comment] 2016-10-14 22:50
how do i read this xml file above?

**Comment by dlebauer** [comment] 2016-10-14 23:11
... it's json but that is all I know, I think the geometries are in WKT format. If you prefer postgis you can import this dump of the database https://terraref.ncsa.illinois.edu/bety/dump/bety.tar.gz and look at the sites table, but it should be very similar (for the record the database dump includes metadata but excludes all of the trait data until we make it public).

**Comment by anfrench** [comment] 2016-10-14 23:41
Ok , looks like I have some reading to do, WKT isn’t something I know anything about, I tried the ArcGIS JSON conversion tool and it failed. Maybe QGIS will handle more easily.
Since the issue was raised I created one-row polygons. The attached will need to be checked and edited, it has one polygon per one-row plot and includes buffers between plots (but not buffers on the outside).

**Comment by dlebauer** [comment] 2016-10-15 04:15
@anfrench I think Wasit or Matt can do this, as it will be a good opportunity for them to give me feedback on the data formats and how they can interoperate.

**Comment by Mamatemenrs** [comment] 2016-10-15 23:12
We can work with the shapefile that Rick has been using after it is confirmed. I'll further check with Wasit though. 

Thanks.

**Comment by dlebauer** [comment] 2016-10-25 16:24
@Mamatemenrs have you had a chance to compare the data in betydb with the shapefile? It looks like we will need to insert new bounding boxes in the database that correspond to the interior two row subset.

**Comment by Mamatemenrs** [comment] 2016-10-25 19:53
Anyone can confirm what is the coordinate system and datum on the JSON file? I see geographic long/lats, but wondering the datum? Currently, it does not align with the file Rick shared.

**Comment by dlebauer** [comment] 2016-10-25 20:01
@Mamatemenrs I think it is WGS84. Please confirm with @tingli3

**Comment by dlebauer** [comment] 2016-10-26 03:43
@mamatemenrs can you show a map overlaying the two?

@mamatemenrs and/or @tingli3 can you convert the shapefile to a postgis insert statement?

**Comment by Mamatemenrs** [comment] 2016-10-26 04:45
Tried to open the JSON file in QGIS and it only opened part of the shape file, but still able to overlay them somehow. Basically, they don't align.

![gantry_shp](https://cloud.githubusercontent.com/assets/22641377/19713531/737e3c38-9b0c-11e6-9d00-4c6fbdada6d6.jpg)

**Comment by dlebauer** [comment] 2016-10-26 05:02
@Mamatemenrs to start, can you output a version of Ricks shape file that looks like the json file? (Only sitename and geometry fields are necessary)

@smarshall-bmr and @tingli3 can you please try to resolve these differences?

**Comment by anfrench** [comment] 2016-10-26 05:19
The two sorghum trials have different plot layouts, they will not align. I think there are 8 'ranges' in first one and 7 in the second. What we are going for is season 2 as noted earlier by @dlebauer above. If I knew how betdb works I could see about converting the shape file to json format in scanner coordinates; i created the shp files in UTM zone 12 using WGS84 via proj4 library in R.

**Comment by Mamatemenrs** [comment] 2016-10-26 13:52
Here is JSON format of Rick's file.  projection is UTM zone 12 using WGS84.

[Rick_JSON.zip](https://github.com/terraref/computing-pipeline/files/553385/Rick_JSON.zip)

**Comment by rickw-ward** [comment] 2016-10-26 15:01
Shape files of current (10-26-16) sorghum layout at MAC are at: https://drive.google.com/open?id=0B5btztQSCEFxVUZ6SlRHVDBpdWM .

Original file of foundation xyz from USDA RTK is in this zip:
[foundation shape file.zip](https://github.com/terraref/computing-pipeline/files/553648/foundation.shape.file.zip)

orthomosaic as geotiff from four weeks ago (NDVI) from UAV flight is at: https://drive.google.com/open?id=0B5btztQSCEFxYjZDTzJwWkctVWM

When I put all of the above in a QGIS project, all features align.  Note the plot polygons would not align with the first sorghum crop of this year (April to July).

**Comment by dlebauer** [comment] 2016-10-26 15:30
@rickw-ward et al 

* I think that the shape files Rick linked to above are the same listed in my original task description.
* The foundation points are an additional data set that would be useful to archive with metadata ( @craig-willis )
* I believe that the plots in the image above labeled "David" are from season 1. 
  * We need something similar for season 2, which should be available at http://terraref.ncsa.illinois.edu/bety/api/beta/sites?sitename~Season+2&limit=none&key=
  * I don't expect those to align - I expect that there will be two plots for every one plot in the shape file. These match the boundaries of the two-row subplots in [Maria's dataset](https://docs.google.com/spreadsheets/d/1B30WB5vD-JAU2Pgluhdu1kIxwttdOcQphSIin7BByKg/edit#gid=1624063516) and the [gantry measurements](https://github.com/terraref/computing-pipeline/issues/174#issuecomment-249327822) that Stewart took for season 2

**Comment by rickw-ward** [comment] 2016-10-26 15:32
Is there significance to the fact that the season one plots are geo-located in only the south 1/5 of those for the current season?

**Comment by dlebauer** [comment] 2016-10-26 15:39
@rickw-ward that is just the first 200 records returned by default since I forgot to add `&limit=none` to the API call.

**Comment by rickw-ward** [comment] 2016-10-26 15:41
It appears to be shifted south two ranges, which should not be the case.  But perhaps an artifact.

**Comment by dlebauer** [comment] 2016-10-26 18:02
@anfrench do you have the R code and original data that you used to generate these polygons?

**Comment by anfrench** [comment] 2016-10-26 21:40
[Sorghum2_DataFile_AugustPlanting.csv.txt](https://github.com/terraref/computing-pipeline/files/554489/Sorghum2_DataFile_AugustPlanting.csv.txt)
[makeshape_F13B2_Fall2016.r.txt](https://github.com/terraref/computing-pipeline/files/554490/makeshape_F13B2_Fall2016.r.txt)

**Comment by tingli3** [comment] 2016-10-27 20:18
The polygons I generated are based on the [plot plan](https://docs.google.com/spreadsheets/d/1QQaWc0UaQQKfEtnSO1G2za8tKU2huC0_VYMBqm5CKAo) and [field book]( https://docs.google.com/spreadsheets/d/1eQSeVMPfrWS9Li4XlJf3qs2F8txmddbwZhjOfMGAvt8/edit#gid=883764630), which has 54 ranges and 16 columns (32 rows) in total. The coordinates of gantry field are converted into latitude and longitude (in WGS84) with [coordinates summary](https://docs.google.com/spreadsheets/d/1pTgmpf9kltYW1SHo_K51cynVTYs6-JdS6rt4usfwV10). 

What are the data source of these two files?
[Sorghum2_DataFile_AugustPlanting.csv.txt](https://github.com/terraref/computing-pipeline/files/554489/Sorghum2_DataFile_AugustPlanting.csv.txt) and the
[makeshape_F13B2_Fall2016.r.txt](https://github.com/terraref/computing-pipeline/files/554490/makeshape_F13B2_Fall2016.r.txt)? Is this the ground truth?

**Comment by dlebauer** [comment] 2016-10-27 20:30
@tingli3 I think you can ignore those files since they were used to generate a [shape file](https://github.com/terraref/computing-pipeline/files/530579/sorghumexpfall2016v5.zip) that @Mamatemenrs has exported as [json](https://github.com/terraref/computing-pipeline/files/553385/Rick_JSON.zip). The next step is to create the BETYdb insert statements for these polygons - they will be listed as new 'sites'. But instead of `Plot 123` the sitename field should have `Row x Col y` (where x and y are integers of the row and column fields).

**Comment by tingli3** [comment] 2016-10-27 21:45
@dlebauer 
Can you give me some example of the insert statements I should generate? Or what does the table I will be working on look like? 

What do you mean by "they will be listed as new 'sites'. But instead of Plot 123 the sitename field should have Row x Col y (where x and y are integers of the row and column fields)" ?

**Comment by rickw-ward** [comment] 2016-10-27 21:56
Please retain the data for range and pass and note just rowxcol.

**Comment by tingli3** [comment] 2016-10-27 22:08
Also, the shape file is projected in UTM 12 N. Should the output coordinates XY be converted to WGS84 or still kept in UTM?

**Comment by dlebauer** [comment] 2016-10-27 22:15
@tingli3 same table (BETYdb sites) and insert statements as #174. Row and col values Come from the shape file and should be used in the plot name. Like `sitename = Field Scanner Season 2 Row 1 Col 1`

@rick-ward please specify a standard plot naming scheme if you prefer.

**Comment by dlebauer** [comment] 2016-10-27 22:16
@tingli3 same projection as #174 as well

**Comment by rickw-ward** [comment] 2016-10-27 22:23
https://github.com/anfrench, see questions above about UTM vs WGS84 above.

**Comment by rickw-ward** [comment] 2016-10-27 22:32
For the RIL experiment, the experimental units have addressses composed of two variables: range and pass.   Those, plus the entry number, replication, blocks within reps, etc. can be retrieved through a shared, unique plot#.     Range-Pass enables instant recognition of where an experimental unit is, and is the grid system used for planning envelope filling, planting, and plot labeling.    Not sure this is helping much though...

**Comment by NewcombMaria** [comment] 2016-10-28 14:50
I wonder if it would be helpful in this plot-boundary issue/discussion to define some terminology, or come up with standard definitions in the context of a data or metadata dictionary.  A 'Range' extends in the Y direction (East-West) and in sorghum crop1 and sorghum crop2 there have been 54 ranges.  A 'Row' extends in the X direction (North-South) and in sorghum crop1 and sorghum crop2 there have been 32 rows.  With sorghum crop1 it was useful to use the term 'Column' to represent 2-rows, since crop1 had 2-row plots and also 2-row border plantings on the West and East sides (16 'columns' was a useful concept).  In the design for sorghum crop2, the term 'Pass' has been used.  Sorghum crop2 has 2-row border plantings on the West and East sides, and 4-row plots (7 experimental plots per range) and it's more useful to refer to 32 rows rather than 16 columns for the sorghum crop2.  I hope this might be helpful, to standardize terms and come up with common definitions.

**Comment by dlebauer** [comment] 2016-10-28 16:55
Lets move discussion of the plot definitions here: terraref/reference-data#60

**Comment by anfrench** [comment] 2016-10-28 20:45
@tingli3 at the risk of saying things you already know: WG84 is a reference ellipsoid. UTM zone 12 is a projection. Projections need a corresponding ellipsoid. In the NAD83 system that ellipsoid is GRS80, not WGS84, but they are very nearly the same.
When you create a latlon to UTM transformation in proj4 (PROJCS) you specify the semi-major axis and flattening.
GRS80 is 6378137m; 1/298.257222100882711...
WGS84 at one time was the same as GRS80, but is now:
6378137 m (same); flattening a bit different 298.257223563
This is all to say that the shape Ive provided for the sorghum trial #2 is a projection to UTM zone 12 using the WGS84 ellipsoid. I think we should continue using WGS84 ellipsoid.

**Comment by Mamatemenrs** [comment] 2016-10-29 17:09
Shapefiles for seanson2

Projected Coordinate System for both files: WGS_1984_UTM_Zone_12N

![season2 plys](https://cloud.githubusercontent.com/assets/22641377/19831468/37fda1d2-9dd0-11e6-96d2-60e4015fec55.jpg)

**Comment by remotesensinglab** [comment] 2016-10-29 18:04
Can tingli3 or dlebauer

**Comment by Mamatemenrs** [comment] 2016-10-29 18:10
Season 2 shapefiles

Projected Coordinate System for these files:	WGS_1984_UTM_Zone_12N

![season2 plys](https://cloud.githubusercontent.com/assets/22641377/19831802/c9b482fa-9dd8-11e6-8b6b-9d0beb59e692.jpg)

**Comment by dlebauer** [comment] 2016-10-29 18:51
@remotesensinglab the plots from BETYdb json file were generated thus:  https://github.com/terraref/computing-pipeline/blob/master/scripts/geospatial/field_scanner_plots.R; @tingli3 can comment on technical details.

It looks like Ricks shp file plots are a subset of Tings json plots, and close enough that there represent the same concept of a plot but different enough that this represents measurement error. For aligning UAV and gantry data I suggest going with the plot boundaries  derived from gantry measurements.

So Matt can get started I'd suggest extracting means for the superset of plots. We can group Ricks plots as appropriate for analysis and drop the others if they are contain mixed genotypes. 

Rick - am I correct that the ones that do not overlap your plots have two border rows of different genotypes?

**Comment by rickw-ward** [comment] 2016-10-31 15:47
Something is amiss.   The array of Polygons from andys ('ricks') shape file should be aligned east west at the same center point as the yellow polygons.  But they aren't.  The yellow is shifted significantly east   Why?  Can someone send. E the two shape files and I'll check them in qgis.

**Comment by rickw-ward** [comment] 2016-10-31 18:34
@anfrench and I just discussed the frameshift of yellow vs red polygons.  This included a reveiw of the R script here https://github.com/terraref/computing-pipeline/blob/master/scripts/geospatial/field_scanner_plots.R .   Query for @smarshall-bmr and @dlebauer, what point in the field is zero, zero for the gantry?   in attached screen shot of QGIS with layers of orthomosaic geotiff of field/gantry, polygons of middle two rows of plots, and foundation centers (visiblly aligned with geotiff), the text box is pointing at a red dot positioned 2m east of Y coordinate of what I think is the Lemntatec zero,zero point.  If so, and that is used as a corner of plots, it would explain the eastward shift of the yellow polygons.
<img width="2560" alt="screen shot 2016-10-31 at 11 17 43 am" src="https://cloud.githubusercontent.com/assets/21243879/19866098/07899078-9f5c-11e6-9fcb-e3dcab63be59.png">

**Comment by Mamatemenrs** [comment] 2016-10-31 19:53
Shapefiles for the second map on this page.

[Rick_David_shps.zip](https://github.com/terraref/computing-pipeline/files/562750/Rick_David_shps.zip)

**Comment by rickw-ward** [comment] 2016-10-31 21:22
thanks @Mamatemenrs .   I pulled your json file into my QGIS project, and also added a shape file from @rjstrand  at Lemnatec with a single feature that is Lemntatec's (ie. the gantry's) zero,zero point (red dot above feature attributes box).   The east edge of your east-most plot  (green polygons) is closely aligned with the Y axis position of the Gantry zero,zero.   But that point is outside of the actual planted area.  If your polygons are based on that as the east most point of the Y axis, it would explain why they are shifted one row east of ours (pinkish polygons over two middle rows of four row plots; note two rows of buffer to east and to west of 7 4-row plots in a range.

<img width="2560" alt="screen shot 2016-10-31 at 2 17 37 pm" src="https://cloud.githubusercontent.com/assets/21243879/19872102/59519324-9f75-11e6-98ff-81a0c1fd96e1.png">

**Comment by rickw-ward** [comment] 2016-11-01 16:31
@ZongyangLi  and @rmgarnett .  See the thread above.  My perspective is strictly 2D at this stage.

**Comment by rickw-ward** [comment] 2016-11-02 14:39
Any updates @dlebauer or @Mamatemenrs ?

**Comment by Mamatemenrs** [comment] 2016-11-02 14:54
I do not have anything to update regarding these shapefiles.

**Comment by tingli3** [comment] 2016-11-02 16:21
[new_sql.txt](https://github.com/terraref/computing-pipeline/files/567097/new_sql.txt)
This is the sql generated for the shapefile.  Not sure about whether the shift from UA-MAC to USDA should be applied. Currently, the coordinates are just transfromed from UTM12.

**Comment by dlebauer** [comment] 2016-11-03 04:01
@tingli3 from the figure in https://github.com/terraref/computing-pipeline/issues/187#issuecomment-257424469 it looks like your R code from #174 may have two issues: 
1. the eastern side of the plot boundaries is aligned to y = 0, whereas the minimum value of y measured by @smarshall-bmr on the gantry was 0.632 ([see spreadsheet](https://docs.google.com/spreadsheets/d/1eQSeVMPfrWS9Li4XlJf3qs2F8txmddbwZhjOfMGAvt8/edit#gid=1433617856). 
2. The plots are adjacent to one another. However the same measurements indicate that there is a gap of 20 cm between each plot on the x (NS) axis. 

@smarshall-bmr Your measurements indicate a 20 cm gap but I believe that @NewcombMaria said these were intended to be ~50 cm, and this is closer to @rickw-ward's map and observations.

**Comment by tingli3** [comment] 2016-11-03 05:00
@dlebauer 
For the first issue, I have asked question about the start of y more than once and I got no answer. So I have to assume y start at 0 and I wrote this assumption when I uploaded the sql for the first time. There are only 32 records of y and I need 33 records to get 32 rows so I have to assume y start at 0.

For the second issue, if you look at
![gantry_shp](https://cloud.githubusercontent.com/assets/22641377/19713531/737e3c38-9b0c-11e6-9d00-4c6fbdada6d6.jpg), there is a gap though the file is incomplete. I am not sure why the gap disappears in the pictures later.

**Comment by smarshall-bmr** [comment] 2016-11-03 18:52
For what it's worth I have updated the range centers document to include row boarders. All I did was place midpoints between each row and use the average row width to place a start and end point.

**Comment by dlebauer** [comment] 2016-11-03 21:04
@ZongyangLi when you used the plots as defined by Stewart, did you realize that his measurements were the plot centers rather than the plot boundaries?

**Comment by ZongyangLi** [comment] 2016-11-03 21:43
@dlebauer To my understanding, 54 ranges in N/S direction is the centers and 16 rows in W/E direction is the boundaries, is that right?

**Comment by dlebauer** [comment] 2016-11-08 04:54
@zongyangli yes that sounds correct

**Comment by rickw-ward** [comment] 2016-11-08 14:22
does focusing on 16 units e/w preclude consideration of the middle two rows of a single, four-row plot since those two middle rows will be in separate units?   Does it not make sense to make a boundary for each row separately instead of two rows units?

**Comment by dlebauer** [comment] 2016-11-08 15:02
We can have many ways to define plots - single, double, quadruple rows.
This should be driven by use cases, only different when necessary, and
hierarchical where possible. So if you define the plot shapes and names we
can generate them.

**Closed** 2016-11-17 15:38 UTC

**Comment by dlebauer** [comment] 2017-01-27 18:11
@rmgarnett FYI
