### ISSUE TITLE
plantcv extractor code integration

### ISSUE THREAD

**Issue by yanliu-chn** [terraref/computing-pipeline#28] opened 2015-11-09 15:36 UTC
Need Rob's help to get dockerfile part and extractor source code into the two code repos on opensource.ncsa.illinois.edu

**Comment by dlebauer** [comment] 2015-11-19 17:43
@yanliu-chn does this duplicate #10?

**Comment by yanliu-chn** [comment] 2015-11-19 18:01
I don't see any overlapping. #10 is to define statement of work.

**Comment by dlebauer** [comment] 2015-11-19 20:08
@yanliu-chn sorry wrong repository. I meant - is this a duplicate of #13

**Closed** 2016-01-21 15:38 UTC
Labels: 3 - Review
