### ISSUE TITLE
Add clowder dev. envt to terraref/clowder-dev

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#184] opened 2016-10-13 19:57 UTC
user can select data, launch clowder dev environment

**Comment by craig-willis** [comment] 2016-10-16 18:42
@max-zilla two questions: 

The tool server container appears to be running, but the analysis environment dropdown in the clowder-dev instance is empty.  Is there something that needs to be configured in the clowder-dev instance?

I'm trying to use JupyterLab as a development environment for pyClowder. JupyterLab uses Python3, but it looks like pyClowder requires 2.x? If this is the case, I'll customize the JupyterLab environment to also install Python 2.x.

**Comment by craig-willis** [comment] 2016-10-27 16:44
@robkooper Please provide updated RabbitMQ password for dev instance.

**Comment by craig-willis** [comment] 2016-10-28 14:36
@robkooper 
I have a working pyClowder development environment on clowder-dev. However, when I upload a file, the extractor immediately gets a 502 (HTTPError: 502 Server Error: Bad Gateway for url: https://terraref.ncsa.illinois.edu/clowder-dev/api/files/58136174e4b03d6eb3588568/metadata.jsonld?...)  I've seen this error with the sensor data too -- if I GET immediately after a POST, I see a 502. If I wait a few seconds, it goes away.  

Any advice?

**Comment by max-zilla** [comment] 2016-10-28 14:40
@robkooper this could be that same ElasticSearch indexing issue we were talking about yesterday - the metadata gets posted but 502 trying to index it (maybe). i havent tried the local test yet

**Comment by craig-willis** [comment] 2016-10-31 17:53
@dlebauer @max-zilla 
I have Cloud9/pyClowder and JuptyerLab/pyClowder environments installed on clowder-dev.   Both of these support basic extractor development with the following steps:

- Launch the desired tool
- For Cloud9, login with hardcoded credentials (terra/pyclowder) -- see note below about auth
- Open terminal
- For JupyterLab, "export PATH=/usr/bin:$PATH" -- this is because JupyterLab requires python3 (default), but pyClowder requires python2.x.
- git clone https://opensource.ncsa.illinois.edu/bitbucket/scm/cats/pyclowder2.git 
- cd pyclowder2/
- pip install -r requirements.txt --user
- python setup.py install --user
- cd sample-extractors/wordcount/
- To bypass 502 error above: open Clowder UI, upload a file to the dataset then wait 5-10 seconds
- python wordcount.py --rabbitmqURI amqp://clowder:secret@rabbitmq.ncsa.illinois.edu/clowder-dev   --rabbitmqExchange terra

A few notes:
- The Cloud9 image could just as easily be any web-based development environment (e.g., Wetty+vi/emacs).  
- Neither environment supports interactive debugging.
- User authentication will be an ongoing problem. NCSA Security is now monitoring Nebula and looking for open applications, particularly IDEs with shells.  TERRA will need to address this with these containers at some point.
- As noted in earlier comments, the RabbitMQ password will need to be changed in the dev environment and the 502 error resolved before this is generally usable.
- On a site note, for NDS Labs we now have an nginx-proxy solution to the Docker port range problem.  We run an nginx proxy that rewrites requests to host:port/containerId instead of opening the whole range of Docker ephemeral ports. 

Feedback welcome.

**Comment by dlebauer** [comment] 2016-11-03 16:26
@craig-willis I don't any tools to launch

<img width="353" alt="screen shot 2016-11-03 at 11 25 43 am" src="https://cloud.githubusercontent.com/assets/464871/19974999/61e92818-a1b8-11e6-8dbb-e6e2445840d4.png">

**Comment by craig-willis** [comment] 2016-11-03 17:02
@dlebauer Unclear why, but the toolserver process was stopped again.  I've restarted and will look through the logs, but you should be able to launch now.

**Comment by rachelshekar** [comment] 2016-11-14 19:55
is this running now?

**Comment by craig-willis** [comment] 2016-11-14 20:13
There are still a few open issues:
* Are the provided Cloud9/pyClowder and JupyerLab environments acceptable?
* If so, I'll need to officially publish these via NDS Labs before closing.
* As far as I know, the 502 error from Clowder is still there, but should probably be a separate issue
* The Tool Server seems to go down periodically, but unrelated to this ticket and should probably be a separate issue
* Finally, we need to have a discussion about authentication into these tools.  With NCSA scanning Nebula now, there's a chance that unauthenticated instances will be blackholed.  Can also be a separate ticket.

So, if the provided environments are acceptable for now, after publishing the official ndslabs image and creating the 3 additional tickets, this one can be closed.

**Comment by dlebauer** [comment] 2016-11-17 15:51
@craig-willis I'd say great - go ahead and publish these.

However, the tool server crashed. Please open a separate issue. Or maybe someone else on the team (@jterstriep?) can assist?

**Comment by craig-willis** [comment] 2016-11-17 15:58
Thanks, @dlebauer 

I've confirmed that both the dev and production instances of the toolserver are currently running. What specifically are you seeing -- the list isn't appearing in Clowder?

**Comment by craig-willis** [comment] 2016-11-18 20:58
Dockerfiles are now part of ndslabs:
https://github.com/nds-org/ndslabs-clowder/tree/master/dockerfiles/devenv

Images available via ndslabs Dockerhub account:
https://hub.docker.com/r/ndslabs/jupyterlab-pyclowder/
https://hub.docker.com/r/ndslabs/cloud9-pyclowder/

Opened #204 to address toolserver authentication/security concerns.

**Closed** 2016-11-18 20:59 UTC
Labels: enhancement
