### ISSUE TITLE
Insert plot level height and / or percent cover into BETYdb

### ISSUE THREAD

**Issue by dlebauer** [terraref/computing-pipeline#193] opened 2016-10-27 16:21 UTC
### Description

@ZongyangLi has generated extractors that summarize plot level phenotypes. The first two are height and percent cover.

These need to be inserted into the BETYdb API. 
### TODO
- [x] Need to make sure that we have plots defined in BETYdb consistent with the geospatial bounding boxes that you used. 
  - Season 2 bounding boxes based on gantry coordinates are here: http://terraref.ncsa.illinois.edu/bety/api/beta/sites?sitename=~Season+2&limit=none&key=
  - See #187 for comparison of two bounding boxes
- [ ] generate a 'PUT' request with one or more values per plot. 
  - This can go in the current extractor or be added to a new extractor
  - See PlantCV extractor for an example of the JSON format
  - the technical documentation here: https://github.com/PecanProject/betydbdoc-dataentry/blob/master/trait_insertion_api.md
  - ask @gsrohde for help

**Comment by max-zilla** [comment] 2016-10-27 20:08
@ZongyangLi here is an example of creating a CSV to push into BETYdb:
https://github.com/terraref/extractors-lemnatec-indoor/blob/master/plantcv/terra.plantcv.py

```
# BETYdb instance information for submitting output CSV (skipped if betyAPI is empty)
betyAPI = "https://terraref.ncsa.illinois.edu/bety/api/beta/traits.csv"
betyKey = "CREATE_USER_ACCOUNT_FOR_A_KEY"

def submitToBety(csvfile):
    global betyAPI, betyKey

    if betyAPI != "":
        sess = requests.Session()
        print(csvfile)
        print("%s?key=%s" % (betyAPI, betyKey))
        r = sess.post("%s?key=%s" % (betyAPI, betyKey),
                  data=file(csvfile, 'rb').read(),
                  headers={'Content-type': 'text/csv'})

        if r.status_code == 200 or r.status_code == 201:
            print("CSV successfully uploaded to BETYdb.")
        else:
            print("Error uploading CSV to BETYdb %s" % r.status_code)
            print(r.text)
```

The CSV file is generated here:
https://github.com/terraref/extractors-lemnatec-indoor/blob/master/plantcv/PlantcvClowderIndoorAnalysis.py
```
# fields are the CSV column headers
fields = ('entity', 'cultivar', 'treatment', 'local_datetime', 'sv_area', 'tv_area', 'hull_area',
              'solidity', 'height', 'perimeter', 'access_level', 'species', 'site',
              'citation_author', 'citation_year', 'citation_title', 'method')
# traits is the dictionary of values for CSV (this script only has 1 row per csv)
    traits = {'plant_barcode' : '',
              'genotype' : '',
              'treatment' : '',
              'imagedate' : '',
              'sv_area' : [],
              'tv_area' : '',
              'hull_area' : [],
              'solidity' : [],
              'height' : [],
              'perimeter' : [],
              'access_level': '2',
              'species': 'Sorghum bicolor',
              'site': 'Danforth Plant Science Center Bellweather Phenotyping Facility',
              'citation_author': '"Fahlgren, Noah"',
              'citation_year': '2016',
              'citation_title': 'Unpublished Data from Sorghum Test Runs',
              'method': 'PlantCV'}

def generate_average_csv(fname, fields, trait_list):
    """ Generate CSV called fname with fields and trait_list """
    csv = open(fname, 'w')
    csv.write(','.join(map(str, fields)) + '\n')
    csv.write(','.join(map(str, trait_list)) + '\n')
    csv.close()

    return fname
```

**Comment by ZongyangLi** [comment] 2016-10-27 21:34
Start working on this. @dlebauer 

- Make sure that we are using same plots definition
      1. For 'Percent Cover' traits, I believe I am using a same plot plan and field book that @tingli3 was using. For now I only generated some Season 1 data. 
      2. For 'plot level height', although we have some of position parameters like 'scan position, scan direction, scan distance' and so on, we don't have enough parameter to locate plots. Ply files can be shown as below:
![range6_3d_0](https://cloud.githubusercontent.com/assets/20230686/19785862/d9a43134-9c60-11e6-9ff6-953c46f58c6e.PNG)
![range6_3d](https://cloud.githubusercontent.com/assets/20230686/19785866/e17fd98a-9c60-11e6-92d1-d024501926f1.PNG)
The most important parameter I need is 'what is the original point represents for'. Before I get this parameter, I have to make a guess like 'the first plant in the ply represents for plot row 2'.  So I don't think it's a good timing to add 'height distribution' into BETYdb. I generated some height distribution data using those ply files in Season 2 and sent it to @rmgarnett to compared with the hand measurements. I am looking forward to his feed back.

- generate a 'PUT' request with one or more values per plot.
         1. I think it should be a new extractor for 'percent cover' data into BETYdb, it is different from those geotiff creations. 
         2. @max-zilla Thanks for these examples! I will try this.

**Comment by ZongyangLi** [comment] 2016-10-28 15:49
@dlebauer I am writing to let you know my plan of this task, please let me know if I made any misunderstanding.

1. Get leaf area index value(percent cover) for each vis-image, that means each image have a value to submit.
2. Create a .csv file that records all the information about the trait(location, row#, col#, time and trait value).
3. use clowder extractor to sent this .csv file into BETYdb

**Comment by dlebauer** [comment] 2016-10-28 16:22
@ZongyangLi yes, this is correct. However, instead of using the row and column, you will need to construct a `sitename` field.

* Currently they are constructed as `MAC Field Scanner Field Plot <plotid>` 
  * For season 1 these will match the records here that do not include "Season 2" https://terraref.ncsa.illinois.edu/bety/api/beta/sites?sitename=~Field+Scanner&limit=none&key=
  * do you have the plot # or just the row # and col #?
* In addition to passing a single value like 'canopy_cover', you can optionally insert a sample size and statistic (like SD). We can define how this is computed in the method protocol.

**Comment by dlebauer** [comment] 2016-10-28 16:24
@ZongyangLi regarding the position of the points in the ply files - I was under the impression that these were in the gantry xyz coordinate system. If this is not the case, please open a separate issue and assign to @solmazhajmohammadi.

**Comment by ZongyangLi** [comment] 2016-10-28 16:39
@dlebauer I am not quite understand the link above? 
`{
  "metadata": {
    "URI": "https://terraref.ncsa.illinois.edu/bety/api/beta/sites?sitename=%7EField+Scanner&limit=none&key=",
    "timestamp": "2016-10-28T11:29:24-05:00",
    "count": null
  },
  "errors": "authenication failed"
}`
Is that means I should construct a `sitename` field in the .csv file that contains of 'timestamp, cont, errors'? 
I use a [plot plan](https://docs.google.com/spreadsheets/d/1QQaWc0UaQQKfEtnSO1G2za8tKU2huC0_VYMBqm5CKAo/edit#gid=1066629008) and [field book](https://docs.google.com/spreadsheets/d/1eQSeVMPfrWS9Li4XlJf3qs2F8txmddbwZhjOfMGAvt8/edit#gid=883764630) to get a plot # base on the gantry position.

**Comment by dlebauer** [comment] 2016-10-28 16:57
@ZongyangLi you need a key. Try https://terraref.ncsa.illinois.edu/bety/api/beta/sites?sitename=~Field+Scanner&limit=none&key=9999999999999999999999999999999999999999

**Comment by dlebauer** [comment] 2016-10-28 16:59
@ZongyangLi if you use the plot numbers in the field book and construct the sitename as  `MAC Field Scanner Field Plot <plotid>` where `<plotid> is [1, 2, ...849] that will work.

**Comment by remotesensinglab** [comment] 2016-10-28 18:11
Has anyone measured in-situ leaf area index, vegetation fraction so that can be used to validate/refine extraction algorithms?

**Comment by dlebauer** [comment] 2016-10-28 18:15
@remotesensinglab there is radiation interception but I am not sure of LAI - @NewcombMaria would know

**Comment by dlebauer** [comment] 2016-10-28 18:18
@remotesensinglab I think this issue just refers to % cover - it seems like the camera is the most accurate way to directly measure this, and most of any error would come from the identification of leaf vs soil. This isn't a direct measure of LAI. By 'vegetation fraction', do you mean 'canopy cover'?

**Comment by remotesensinglab** [comment] 2016-10-28 18:21
Yes, Fraction of Vegetation = canopy cover in %, which is different than LAI.

**Comment by dlebauer** [comment] 2016-10-28 22:37
For these heights, the json trait snippet from above would look more like this:

```json
    traits = {'local_datetime' : '',
              'canopy_cover' : [],
              'access_level': '2',
              'species': 'Sorghum bicolor',
              'site': 'Maricopa Field Scanner Plot <plot #>',
              'citation_author': '"Andrade, Pedro"',
              'citation_year': '2016',
              'citation_title': 'Maricopa Field Station Data and Metadata',
              'method': 'Canopy Cover Estimation from RGB images'}
```

notes: In order for this to work I manually created the variable [`canopy_cover`](https://terraref.ncsa.illinois.edu/bety/variables/6000000012) and method [(see here)](https://terraref.ncsa.illinois.edu/bety/methods/6000000002) via the web interface since we don't have api's for inserting metadata into these tables (or citations etc).

**Comment by ZongyangLi** [comment] 2016-10-31 20:03
@max-zilla I have just finished [terra_canopyCover.py](https://drive.google.com/open?id=0B5QCp_Onc6nOa1Z2dTlDc1lydW8) extractor on 'Canopy Cover' and tested it on my desktop(made little change in config). Could you review these codes and help me test it?

@dlebauer The example .csv file is [here](https://drive.google.com/open?id=0B5QCp_Onc6nOVVFvSm90ZmdzaW8), could you please take a look on it and tell me if it works?

**Comment by max-zilla** [comment] 2016-10-31 20:11
@ZongyangLi Yes I'll try to look at it in next couple days.

**Comment by dlebauer** [comment] 2016-10-31 21:22
@ZongyangLi that looks good except:

* the sitename should match one of these exactly https://terraref.ncsa.illinois.edu/bety/sites
* this is not essential - since we can fill this in later - but there should be a cultivars field that contains the name of the genotype that was planted in the plot, It should be possible to look this up based on the entry field 'entry' here: https://docs.google.com/spreadsheets/d/1QQaWc0UaQQKfEtnSO1G2za8tKU2huC0_VYMBqm5CKAo/edit#gid=796817704

**Comment by ZongyangLi** [comment] 2016-10-31 21:41
@dlebauer 
I still feel a little confused.
1. So I should use the 'Entry Number' instead of 'Plot Number' in the google sheet?
2. If point 1 is yes, why there are totally 864*4 different plots in the sites page, like
`MAC Field Scanner Field Plot 864
MAC Field Scanner Field Plot 864 E
MAC Field Scanner Field Plot 864 W
MAC Field Scanner Field Plot 864 Season 2`
shouldn't it be 401 different 'Entry Number'?

**Comment by dlebauer** [comment] 2016-10-31 21:50
@ZongyangLi 

* Use plot number, not entry number
  * We can use plot number to look up the genotype name later so you don't have to worry about entry number.  (genotype name is in the ['source' field here](https://docs.google.com/spreadsheets/d/1QQaWc0UaQQKfEtnSO1G2za8tKU2huC0_VYMBqm5CKAo/edit#gid=796817704) and that would map to cultivars.name). But again, ignore this if it is confusing. 
* Don't worry about E and W - we have a heirarchy of plots, and these were created to account for the fact that Maria measured the E and W rows separately.
* For Season 1, please use the ones that do not specify direction or season since these are the bounding boxes you used to subset the data. 

We standardize the site names when we resolve terraref/reference-data#60

**Comment by gsrohde** [comment] 2016-11-01 16:03
@ZongyangLi One other small (but important!) detail is that the date (`local_datetime`) should be in the form `2016-06-06T11:28:06`.  (For what it's worth, the GitBook documentation explains this here: https://pecan.gitbooks.io/betydbdoc-dataentry/content/trait_insertion_api.html, in item 1.ii. of the section "Schema for CSV Data Files".  This documentation is still in progress, however, so the numbering or section titles may change.)

If you edit your CSV files in Excel rather than in a text editor, Excel may automatically format dates in a certain way.  And if you then export to CSV, I'm not sure whether or not you get a date that looks exactly as it did in the Excel spreadsheet.

**Comment by ZongyangLi** [comment] 2016-11-01 16:28
@dlebauer @gsrohde 
Thanks for giving me these information!
I have just update my scripts. And now it looks like this: [ccTraits.csv](https://drive.google.com/open?id=0B5QCp_Onc6nOcUYtWTBsQXlUN3M)

**Comment by max-zilla** [comment] 2016-11-01 20:14
@ZongyangLi I'm starting to look at extractor - it looks like this operates on the left/right stereo bin files, correct?

I'm thinking I'll commit this here if so: https://github.com/terraref/extractors-stereo-rgb

**Comment by ZongyangLi** [comment] 2016-11-01 20:21
@max-zilla Yes, that's right. Please review [this scripts](https://drive.google.com/open?id=0B5QCp_Onc6nORm0yYnB2bHBKOTQ), I have just make some update.

**Comment by max-zilla** [comment] 2016-11-01 20:30
@ZongyangLi thanks. I have put your latest code in this repo:
https://github.com/terraref/extractors-stereo-rgb/tree/canopycover/canopycover

Currently just my branch, but I'll merge soon and then we can update this copy directly.

**Comment by ZongyangLi** [comment] 2016-11-07 22:40
@dlebauer Please review the [canopycover datasets](https://drive.google.com/open?id=0B5QCp_Onc6nOZ3Zsa044REdva0E) in May. I put one days data in a csv file.

**Comment by dlebauer** [comment] 2016-11-07 23:04
@ZongyangLi that looks great - only problem is that the date should have format `YYYY-MM-DDTHH:MM:SS` instead of `MM/DD/YYYYTHH:MM:SS`.

**Comment by ZongyangLi** [comment] 2016-11-07 23:09
@dlebauer My bad. This should be work!

[https://drive.google.com/open?id=0B5QCp_Onc6nOMFRwZjdCcl9hOWs](https://drive.google.com/open?id=0B5QCp_Onc6nOMFRwZjdCcl9hOWs)

**Comment by dlebauer** [comment] 2016-11-07 23:13
@max-zilla should we upload these directly to BETYdb or will the extractor do this?

**Comment by ZongyangLi** [comment] 2016-11-07 23:18
@dlebauer 
I also create a height distribution from ply files. It records total number of points in a height level. For example, Z coordinates is divided into 400 levels, assuming level 65 is the ground plane, level 65 may contains 120000 points from the point cloud data. I'm not sure how to build the csv file. Could you give me a field name of the csv file as canopy cover above?

**Comment by dlebauer** [comment] 2016-11-07 23:33
@ZongyangLi For each plot, could you find the height that contains 95% of the points and provide this height (in units of meters above the ground) as the trait 'height' with method '95th quantile point cloud' or something along these lines?

**Comment by dlebauer** [comment] 2016-11-07 23:33
@ZongyangLi alternatively, you could just call the trait '95th_quantile_height'.

**Comment by ZongyangLi** [comment] 2016-11-08 20:29
Here is the plant height estimation using 3d Scanner data  in season 2(in units of meters):
[https://drive.google.com/open?id=0B5QCp_Onc6nOM1R4TUZQdTdwSkU](https://drive.google.com/open?id=0B5QCp_Onc6nOM1R4TUZQdTdwSkU)

Assuming that the lowest point is the ground plane.

Below is an easy way to show these data:
[https://drive.google.com/open?id=0B5QCp_Onc6nOdzI0VzExZ1o0dzQ](https://drive.google.com/open?id=0B5QCp_Onc6nOdzI0VzExZ1o0dzQ)

**Comment by dlebauer** [comment] 2016-11-08 22:47
@gsrohde could you please insert the datasets that Zongyang provided above ([here as a zip file with five csv files, one per date](https://drive.google.com/open?id=0B5QCp_Onc6nOM1R4TUZQdTdwSkU))?

**Comment by dlebauer** [comment] 2016-11-08 22:50
actually @max-zilla and @ZongyangLi is there already an extractor that will put these into BETYdb, or should @gsrohde go ahead and uploads them?

**Comment by gsrohde** [comment] 2016-11-08 22:55
@ZongyangLi    Closer, but not there yet.  The date should have the form “YYYY-MM-DDTHH:MM:SS” not “MM-DD-YYYYTHH:MM:SS”.  So, for example "05-07-2016T09:42:14” should be “2016-05-07T09:42:14”, assuming “05” is the month and “07” is the day of the month.

**Comment by gsrohde** [comment] 2016-11-08 22:59
@ZongyangLi Sorry -- maybe I wasn't looking at the latest files.  The dates are in the right format in https://drive.google.com/open?id=0B5QCp_Onc6nOM1R4TUZQdTdwSkU.

**Comment by ZongyangLi** [comment] 2016-11-08 23:16
@gsrohde I think you are right, there are two different traits, the first is 'canopy cover', file above is in a wrong format, the right one is here: 
[https://drive.google.com/open?id=0B5QCp_Onc6nOSXRtZjRhU2E3cVU](https://drive.google.com/open?id=0B5QCp_Onc6nOSXRtZjRhU2E3cVU)

The second datasets is 95th quantiles height estimation:
[https://drive.google.com/open?id=0B5QCp_Onc6nOM1R4TUZQdTdwSkU](https://drive.google.com/open?id=0B5QCp_Onc6nOM1R4TUZQdTdwSkU)

@dlebauer There is an extractor for 'canopy cover' but no for 'height estimation'

**Comment by gsrohde** [comment] 2016-11-09 15:55
@dlebauer I will wait to do anything pending @max-zilla and @ZongyangLi's answer whether or not there is an extractor to handle this.

**Comment by gsrohde** [comment] 2016-11-09 16:00
I re-read @ZongyangLi's message and see there is no extractor for 'height estimation', so I will upload that data.

**Comment by gsrohde** [comment] 2016-11-09 16:46
@dlebauer, @ZongyangLi, @max-zilla: OK, the 95th quantile height data is in.  The trait id numbers are 13823–16164.  I had to first add '95th_quantile_height' to the `trait_covariate_associations` table.  (I used 'age' as the (optional) covariate.)

Note that before the canopy cover data can be inserted, either directly via the API or via an extractor, the 'canopy_cover' variable will need an entry in the `trait_covariate_associates` table.  Let me know if I should do this.

**Comment by dlebauer** [comment] 2016-11-09 16:49
@gsrohde I thought we discussed either a) removing the requirements that there be trait_covariate_associations or b) having it auto-populate when a new variable is added. Otherwise, we will keep running into this issue.

**Comment by gsrohde** [comment] 2016-11-09 22:23
@dlebauer I do remember some discussion, but I don't remember what, if anything, we decided.

Thinking about it now, this seems like a reasonable behavior:

1. Any column heading that matches an existing variable name will be recognized as a trait variable except (a) if it is listed in the `trait_covariate_associations` table as a covariate; (b) in the unlikely event that it also happens to match one of the canonical column headings—`citation_author`, `citation_year`, `citation_title`, `citation_doi`, `cultivar`, `species`, `site`, `treatment`, `utc_datetime`, `local_datetime`, `date`, `yield`, `n`, `SE`, `notes`, `access_level`, or `entity`.  (This rule is mainly to prevent everything from breaking if someone somewhat perversely adds one of these unlikely names as the name of a variable.)
2. The use cases for adding a row to the `trait_covariate_associations` table are (a) we wish to recognize a column heading as the name of a covariate variable associated with some (or some set of) trait variable(s); (b) we wish to enforce a requirement for certain trait variables that certain associated covariates always be specified.  (For example, on https://betydb.org, `leafT` must always be specified when trait data for `Vcmax`, `quantum_yield`, `Amax` or certain other variables is uploaded.)

If you agree, I'll make an issue for this and go ahead and implement it.

Note that the tacit assumption here is (and will continue to be, if I implement this) that no variable ever functions both as a primary trait variable and as the covariate of some other trait variable.  (This is only enforced for bulk uploads, either through the Bulk Upload wizard or the API.  You can do whatever you want in this regard when adding or updating traits one-by-one via the _New Trait_ and _Editing Trait_ pages of the BETYdb Web application.)

**Comment by dlebauer** [comment] 2016-11-10 01:06
Yes that sounds correct

**Comment by rachelshekar** [comment] 2016-11-30 15:06
@dlebauer - who should this issue be assigned to?

**Comment by dlebauer** [comment] 2016-11-30 16:08
@rachelshekar I've assigned it to @ZongyangLi. The remaining step is to automate the insertion into BETYdb. For the samples above we uploaded manually, but it should be straightforward to automate this step now that the data and metadata are in the correct format for BETYdb.

**Comment by ZongyangLi** [comment] 2016-11-30 16:32
@dlebauer @rachelshekar 
Extractor codes for 'canopy cover' is now in @max-zilla 's branch: [https://github.com/terraref/extractors-stereo-rgb/tree/canopycover/canopycover](https://github.com/terraref/extractors-stereo-rgb/tree/canopycover/canopycover), i think it is ready for deploy.

Shall we close this issue and open another issue for 'Height distribution' because this creation looks for a set of raw data from clowder like that in 'full field stitched'.

**Comment by dlebauer** [comment] 2016-11-30 17:37
@ZongyangLi yes, please open another issue for 'Height distribution'. 

before closing this, there are a few issues:
* @rmgarnett found that the quantiles do not correlate well with measured height, I suspect because there is a varying fraction of points that represent the soil surface. 
* we currently insert '95th quantile height' but it would be better if we could come up with the best estimate of what a researcher would measure as height in the field, and just call that 'height', differentiating between field and sensor mesurements with the method (rather than variable name).
* for the height distribution - how are you planning to represent this? We could create a few statistical summaries as 'traits' (e.g. 95th quantile, mode, kurtosis, etc). But if we want to provide the height for each of 100 quantiles, we could add this to the metadata where it can be queried via Clowder.

**Comment by max-zilla** [comment] 2016-12-07 16:21
@ZongyangLi i've picked this back up, sorry for the delay. I ran your canopy cover extractor successfully and included it in an update of the demosaic extractor for pyClowder 2. Should be able to deploy this week.

Here's the pull request FYI:
https://github.com/terraref/extractors-stereo-rgb/pull/3/files

**Comment by ZongyangLi** [comment] 2016-12-07 18:17
@max-zilla This is great! Thanks a lot!

**Comment by dlebauer** [comment] 2016-12-07 18:41
@max-zilla when we run the extractor we should compute these values for all plots within a season. For example, for any data after June this would include `select name, geometry from sites where name like 'MAC%Season 2%';`

**Comment by max-zilla** [comment] 2017-01-05 17:18
@ZongyangLi and @pless have a CSV for full field season 2 to upload into BETYdb.

**Comment by dlebauer** [comment] 2017-01-05 21:04
@ZongyangLi for Season 1 and 2 data please just upload the data to google drive and @gsrohde can insert it into BETYdb, but moving forward this extractor should insert the results directly into BETYdb

**Comment by ZongyangLi** [comment] 2017-01-05 21:49
@dlebauer I totally agree with you! 

I think extractor for canopy cover percentage is really close to deploy.

Things for traits from 3d scanner is a little bit different from those in stereo camera as I described in #210 

1. we need a parameter to understand where are the coordinates represent for in the field, with this parameter we can confirm an exactly plot level traits, or this will always be an assumption, and I have to check this assumption in every days data.
2. an individual plot is made up of several ply files, which means I need a set of raw data from clowder as input automatically. Another way of solving this problem is create several traits for a plot for one day if it is acceptable, and that will be much easier.

**Comment by dlebauer** [comment] 2017-01-05 22:03
@ZongyangLi 

> we need a parameter to understand where are the coordinates represent for in the field,..

I am not clear what you mean by "we need a parameter to understand where are the coordinates represent for in the field, " Doesn't each point have an x,y,z coordinate in the gantry coordinate system? We have code for transforming x,y to lat, lon. 

> an individual plot is made up of several ply files, 

If an individual plot is made up of several raw files, is the problem one of being able to identify the files within the plot (a use case for #159) or is the problem that the extractor needs to be triggered on some particular set of files rather than a single dataset? 

While It is possible to add replicate measurements for a single plot (we are already doing this for field data), we should do this when it is scientifically useful and not because of the way that the data are written. If necessary, we should be able to merge the point clouds (for .las there is [lasmerge](http://www.liblas.org/utilities/lasmerge.html) and perhaps there is something similar for .ply files) prior to subsetting to the plot boundaries.

**Comment by ZongyangLi** [comment] 2017-01-05 22:24
@dlebauer 
Each point have an x,y,z coordinate in there individual coordinate system, not in gantry coordinate system, for example, in one days scan, all x coordinates are in range of [-600, 600], y coordinates are in range of [-700, -23000], and there is a parameter in metadata that tells us where is the laser sensor in the gantry system: `"position x [m]": "98.1015","position y [m]": "0",`, but we don't have a parameter tells us the relationship between gantry coordinate system and point cloud coordinate system.

I would prefer the extractor needs to be triggered on some particular set of files rather than a single dataset. It's a good idea of rewriting ply files into a plot level with there boundaries. I believe it demands a really accurate coordinate transfer parameter.

**Comment by ZongyangLi** [comment] 2017-01-09 19:44
@gsrohde Could you please help me uploading [90th percentile](https://drive.google.com/open?id=0B5QCp_Onc6nOTi1MdGhiMlZ4VkU) and [95th percentile](https://drive.google.com/open?id=0B5QCp_Onc6nOZmE5MUt5d1JwSnM) into BETYdb?

**Comment by gsrohde** [comment] 2017-01-10 17:27
@ZongyangLi Did you want me to give you instructions on how to upload these or did you just want me to go ahead and do it myself?

One concern I have is that some of the dates for the 95th_quantile_height data overlap with the set you had me upload earlier (from Nov. 8).  Of course, this is 98 days worth of data whereas the earlier set was only 5 days worth.  Should this data _replace_ the earlier data?

@dlebauer This is a general concern I've had—unintentionally uploading the same data twice (or more).  I'm not sure of the best way to prevent that from happening.

**Comment by ZongyangLi** [comment] 2017-01-10 17:52
@gsrohde It will be great if you can give me instructions on how to upload these by myself.

I believe this data should replace the earlier datas for the 95th_quantile_height from Nov. 8. Datas here have more correlation to the hand measurements.  Could you give me an example of operating BETYdb or a document?

**Comment by dlebauer** [comment] 2017-01-10 18:02
@gsrohde I believe the uploads from Nov 8 were associated with different (but overlapping) plot definitions. So they are not truly duplicates, but we can delete these anyway. Are there any dates uploaded on Nov 8 that were not uploaded at this time?

@ZongyangLi do you also have values for 'height', i.e. those that are estimated based on the model that @rmgarnett fit?

**Comment by ZongyangLi** [comment] 2017-01-10 18:08
@dlebauer Is that a 'height' using:
[hand height] = 28.2cm + 0.661 * [89th height percentile]
Not yet, but it would be quite easy to get that.

**Comment by dlebauer** [comment] 2017-01-10 19:12
Yes ... the variable name should be 'height' and the method should include the formula. 

@rmgarnett also had some thoughts on estimating uncertainty using RMSE in #210. (is that a duplicate issue?). But we can add that later.

**Comment by gsrohde** [comment] 2017-01-10 19:31
@dlebauer The five dates uploaded on Nov. 8 are included in the set we are about to upload.  I will delete them.

@ZongyangLi I will send you upload instructions shortly.  I plan to give instructions on how to upload the data using the `curl` utility if that is OK.  Check to see if you have it installed.

**Comment by gsrohde** [comment] 2017-01-10 20:43
@ZongyangLi The curl command to use is
```
curl -X POST -H "Content-Type: text/csv" --data-binary @NAME_OF_YOUR_CSV_FILE "https://terraref.ncsa.illinois.edu/bety/api/beta/traits.csv?key=YOUR_API_KEY"
```
(This is more-or-less covered in the "Using curl to Upload the Data Samples" section of [BETYdb Data Entry Workflow documentation](https://pecan.gitbooks.io/betydbdoc-dataentry/content/trait_insertion_api.html).)

But you will need to sign up for an account on TERRAref and request creator status in order to get an API key that works.  The guestuser API key (99999999...) won't authorize you to upload data.

To request an account, go to https://terraref.ncsa.illinois.edu/bety/, click the "Register for BETYdb" button, and fill out the form.  I think only the Login, Email, and Password fields are required, but I recommend filling in the Name field as well.  Select Page Access Level "3. Creator" from the dropdown and click "Sign up".

Since there are so many files to upload, you may want to automate the process by wrapping the curl command in a shell script.  Or, if you know Python well enough, you could take Max's Python code in comment https://github.com/terraref/computing-pipeline/issues/193#issuecomment-256754687 as a starting point for your own script.  He uses the Python `sessions` module; you could also just call the curl command from Python using (for example) `subprocess.check_output`.  If you do write a script, you may want to have the script abort if it encounters an error.  That way it will be easier to keep track of which files have been uploaded and which have not.  (You could have the script move successfully-uploaded files to an "uploaded" directory to ensure that you don't upload any file twice.)

If you do encounter an error, send me the error message and I can help figure out what the problem is.  But you may not get any errors—the files I looked at look very similar to the files I successfully uploaded earlier.

**Comment by ZongyangLi** [comment] 2017-01-10 21:22
@gsrohde Thanks! I will follow your instructions and try it myself.

**Comment by ZongyangLi** [comment] 2017-01-12 20:34
95th quantiles height for season 2 uploaded.

**Comment by rmgarnett** [comment] 2017-01-13 22:27
To follow up on @dlebauer's comments, I believe we should be doing some work to reject points lying on the ground from the height distributions before extracting any percentiles. What I propose is to look at the height distributions for each plot before emergence, find (say) the 99th percentile, and store this value/bin as the ground level for that bin. Then, when processing height distributions, we should zero any points at or below that bin before normalizing and extracting percentiles (thus keeping just the plant and rejecting the ground).

This will hopefully help with the problem that varying portions of point cloud points are on the ground throughout the season, but we still can't seem to estimate the height of short plants (< 40cm) very well.

**Comment by rmgarnett** [comment] 2017-01-13 22:41
Using such a technique, we get a more-linear relationship, ignoring the short plants:

<img width="538" alt="screen shot 2017-01-13 at 16 40 00" src="https://cloud.githubusercontent.com/assets/583945/21948189/1b6c647a-d9af-11e6-8c21-9187d38772c7.png">

**Comment by ZongyangLi** [comment] 2017-01-13 22:54
One possibility for problem in short plants might be the incorrect input data:
I happened to notice that in 20160831, almost all of plots have a same highest point level at lv. 83, then I checked the raw ply files, it seems point above lv. 83 was 'disappeared'.

**Comment by rmgarnett** [comment] 2017-01-13 23:00
Indeed, omitting 2016-08-31, things look nicer:

<img width="550" alt="screen shot 2017-01-13 at 16 59 28" src="https://cloud.githubusercontent.com/assets/583945/21948571/b5b3f172-d9b1-11e6-893e-a376c9104178.png">

**Comment by dlebauer** [comment] 2017-03-06 22:58
@rmgarnett and @ZongyangLi what is the status of entering these data into the database?

**Comment by max-zilla** [comment] 2017-03-30 16:14
@ZongyangLi let me know if you have questions about pushing into BETY.

**Comment by ZongyangLi** [comment] 2017-03-30 18:47
@dlebauer 
I think we have two things remain in this issue.
1. Insert existed 'height' trait into BETYdb, using the formula: `[hand height] = 28.2cm + 0.661 * [89th height percentile]`, this can be done this week.
2. To automate the insertion into BETYdb. This might need a support of https://github.com/terraref/reference-data/issues/44 and 'the extractor needs to be triggered on some particular set of files rather than a single dataset'.

**Comment by rmgarnett** [comment] 2017-03-30 19:00
@ZongyangLi Please make sure that the parameters in (1) are easily overridden.  The values you quote are using older, sometimes unreliable data.  I will rerun that correlation analysis.

**Comment by ZongyangLi** [comment] 2017-04-05 15:33
@dlebauer @rmgarnett 
I am working on this, insert existed 'height' trait into BETYdb, using the formula.

There is one question I am not quite sure:
@rmgarnett said 'Note that 2-row plots aren't really used anymore (not since the first season); it's probably best to divide the field into 32 rows by 54 ranges = 1728 plots, for all data from now on.'

So is that a good timing to convert this dataset into 1728 plots instead of 864 plots?

**Comment by rmgarnett** [comment] 2017-04-05 15:40
@ZongyangLi Yes, the 864 plots are _meaningless_ and have been since the beginning of the second planting season last year.

See here: https://github.com/terraref/reference-data/issues/60

The 1728 plots ("1-row") is a much more meaningful and useful division that can be reaggregated as seen fit.

**Comment by rachelshekar** [comment] 2017-04-13 15:54
Regarding plots - see discussion https://github.com/terraref/reference-data/issues/114

**Comment by max-zilla** [comment] 2017-05-03 15:08
This has been deployed and is pushing traits - the plot discussion can play out in another issue and we can make changes spinning out from there.

**Closed by max-zilla** 2017-05-03 15:08 UTC
Labels: BETYdb, downward Looking RGB Camera/Stereo, trait data

**Comment by dlebauer** [comment] 2017-05-10 04:27
I've flagged the 95th quantile height dataset as having errors thus:

```sql
update traits set checked = -1 where variable_id = (select id from variables where name = '95th_quantile_height');
```

It had errors related to the fraction of points at ground level and related to the errors in the scanner calibration.  New heights from a regression model have been inserted in https://github.com/terraref/computing-pipeline/issues/210
