### ISSUE TITLE
Missing json files in some StereoVis folders

### ISSUE THREAD

**Issue by pless** [terraref/computing-pipeline#135] opened 2016-08-02 15:55 UTC
### Description

For some of the StereoVis data, the folders that contain this data do not have the associate json file, so that we don't know where the imagery was taken.  This seems to be for data collected before May 3, 2016.  An example data folder is, which (as of Aug. 2) has no json file.

/MovingSensor/stereoTop/2016-05-02/2016-05-02__13-27-24-453/

**Comment by dlebauer** [comment] 2016-08-02 22:39
I did a quick count of files by extension 
[count_stereotop.txt](https://github.com/terraref/computing-pipeline/files/398302/count_stereotop.txt) using this:

```sh
DIR=/projects/arpae/terraref/raw_data/ua-mac/MovingSensor/stereoTop/
cd $DIR
for f in `\ls $DIR`
do 
    cd $f 
    echo $f
    find -type f | sed -e 's/.*\.//' | sort | uniq -c # http://unix.stackexchange.com/a/237948/19809
    cd $DIR
done
```

Here are some anomalies:

* (as reported above) there was a period in late April when .bin files were generated but not json metadata files. 
* There also appears to be folders with json but no .bin files (e.g. 2016-05-07)
* Others where the number of bin files is not 2x the number of json files (e.g. 2016-05-08) (should be `#.json = 2 * #.bin` since there are two cameras in the stereo pair.


@TinoDornbusch @smarshall-bmr and @jdmaloney can you try to track down the source of this error? Can you tell if they were generated? Did they make it to the cache server?

@jdmaloney now that the data stream is stabilizing, how can we implement some tests (such as each stereoTop folder has two bin and one json file)?

**Comment by smarshall-bmr** [comment] 2016-08-02 23:49
I just checked the cache server, I didn't check every folder but I haven't seen any evidence of these data anomalies. Is it a lot of folders that are incomplete in each case or just a handful?
________________________________

**Comment by jdmaloney** [comment] 2016-08-03 00:35
I spot checked a few on the cache server as well and didn't see the anomalies there.  We have to remember those dates are all pre-pipeline dates, aka before the automatic queuing process we're using now, which by the looks of things after skimming the output file David posted seems to be spot on since it took over in mid-May.  Before that transfers were being done by hand.  After seeing those dates and looking back at emails it seems many of the days with anomalies were days where we were doing some trial runs with parts of the automatic system we have in place now, and things probably just didn't get fully back checked by hand when we were done.  

@smarshall-bmr How are you able to check the gantry-cache server?  I don't think access to it for people outside a few folks at NCSA and the few folks down at UA MAC was intended.  I'm guessing through Globus?

@dlebauer I think we can add spot checking across the sensors a day or so after the data is generated (to ensure all files have had time to make it).  I would just need to know the criteria for what is supposed to be there is.  Brute force checking everything is probably not reasonable on the ROGER side.  We really should trust our software more than that, and I think we can based the results of the dates post implementation.  

Also a more broad question are we at stable data flow?  We've yet to see near the volume of data we were expecting, I don't sit in on some of the calls Max has mentioned where they do updates on field conditions etc., but the amount of data we have now (~ 12TB) is what I thought we were expecting out of 3-4 days not 3-4 months.

**Comment by dlebauer** [comment] 2016-08-03 02:00
Data flow is low because the biggest source of data (VNIR) is not online. Our original estimates are here: https://docs.google.com/spreadsheets/d/1UEwBPG6Y2o-Gp5futzmPvfTbhIcNhY4juVwMojX6SAg and we should revise that sheet now that we have data.

@jdmaloney do transfer logs contain information to create time series of data production rates?

Also note that we don't have the pipeline up so no derived products yet.

**Comment by jdmaloney** [comment] 2016-08-03 03:45
Ah, I see, didn't realize VNIR wasn't online, thought we had all sensors going.

@dlebauer Not exactly, we get time stamps (very accurate ones) upon completion of every transferred file into the gantry-cache.  The logs don't contain the file size however, so you'd have to grab all file paths, get their summed size then divide it over the time specified.  Outside the logs I installed a program on the gantry-cache server called vnstat that tracks cumulative and average data traffic amounts on each of the server's network interfaces, the problem with that being if there is other extraneous data movement (someone pulling or pushing files manually or poking at things) you would get noise in that as it is counting ALL network traffic.

**Comment by rachelshekar** [comment] 2016-09-22 19:41
@jdmaloney - can this issue be closed?

**Comment by jdmaloney** [comment] 2016-09-29 16:12
@rachelshekar Yes

**Closed by jdmaloney** 2016-09-29 16:12 UTC
Labels: 2 - Working <= 5
